
- icon_name: briefcase
  title: 'Lorem Ipsum'
  description: 'Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident'
- icon_name: bar-chart-2 # Renamed from ChartNoAxesColumn
  title: 'Dolor Sitema'
  description: 'Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata'
- icon_name: calendar-check-2
  title: 'Sed ut perspiciatis'
  description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur'
- icon_name: wifi # Placeholder for binoculars
  title: 'Magni Dolores'
  description: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum'
- icon_name: sun
  title: 'Nemo Enim'
  description: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque'
- icon_name: aperture
  title: 'Eiusmod Tempor'
  description: 'Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi'
